export default {
  orderFormId: 'c07b84aaba3f4f0d95e5128fc14d5b70',
  salesChannel: '1',
  loggedIn: false,
  isCheckedIn: false,
  storeId: null,
  checkedInPickupPointId: null,
  allowManualPrice: false,
  canEditData: true,
  userProfileId: null,
  userType: null,
  ignoreProfileData: false,
  value: 29400,
  messages: [
    {
      code: null,
      text: 'O valor dos itens foi alterado',
      status: 'warning',
      fields: {},
    },
  ],
  items: [
    {
      uniqueId: '3DE7708B448D403DB90606CB2347C33D',
      id: '287107498',
      productId: '1902421',
      productRefId: '2021005001970',
      refId: '153869_898_0_P',
      ean: '0005110000000010P',
      name: 'Macacão estampado cinto all is love P',
      skuName: 'P',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2021-10-19T14:13:43Z',
      tax: 0,
      price: 39200,
      listPrice: 39200,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 29400,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'All is love',
        brandId: '1420030275',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/7/25/',
      productCategories: {
        '7': 'Babados',
        '25': 'Macacão',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://babadotop.vteximg.com.br/arquivos/ids/532702-548-806/000511principal--5-.jpg?v=637375143776730000',
      detailUrl: '/macacao-estampado-cinto-all-is-love-2021005001970/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [
        {
          name:
            'discount@price-189b7d15-fb58-4ebf-9f1f-d8371d133e89#98add0f3-1709-4271-97d6-744ad201919d',
          value: -9800,
          rawValue: -98,
          isPercentual: false,
          identifier: '189b7d15-fb58-4ebf-9f1f-d8371d133e89',
        },
      ],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
    },
  ],
  selectableGifts: [],
  totalizers: [
    {
      id: 'Items',
      name: 'Total dos Itens',
      value: 39200,
    },
    {
      id: 'Discounts',
      name: 'Total dos Descontos',
      value: -9800,
    },
  ],
  shippingData: {
    address: {
      addressType: null,
      receiverName: null,
      addressId: '0de25c4057f2487c94f5b8bfe5213b40',
      isDisposable: true,
      postalCode: '14403132',
      city: 'Franca',
      state: 'SP',
      country: 'BRA',
      street: 'Rua José Fernando Peixe',
      number: null,
      neighborhood: 'Jardim Alvorada',
      complement: null,
      reference: null,
      geoCoordinates: [-47.3952751159668, -20.56663703918457],
    },
    logisticsInfo: [
      {
        itemIndex: 0,
        selectedSla: 'Normal- via PAC correios',
        selectedDeliveryChannel: 'delivery',
        addressId: '0de25c4057f2487c94f5b8bfe5213b40',
        slas: [
          {
            id: 'Normal- via PAC correios',
            deliveryChannel: 'delivery',
            name: 'Normal- via PAC correios',
            deliveryIds: [
              {
                courierId: '1008bb9',
                warehouseId: '1_1',
                dockId: '1',
                courierName: 'PAC',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '14bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 2377,
            listPrice: 2377,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '12bd',
          },
          {
            id: 'Expressa - Via SEDEX correios',
            deliveryChannel: 'delivery',
            name: 'Expressa - Via SEDEX correios',
            deliveryIds: [
              {
                courierId: '1e36a94',
                warehouseId: '1_1',
                dockId: '1',
                courierName: 'Sedex',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '11bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 4406,
            listPrice: 4406,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '9bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '5274',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
    ],
    selectedAddresses: [
      {
        addressType: null,
        receiverName: null,
        addressId: '0de25c4057f2487c94f5b8bfe5213b40',
        isDisposable: true,
        postalCode: '14403132',
        city: 'Franca',
        state: 'SP',
        country: 'BRA',
        street: 'Rua José Fernando Peixe',
        number: null,
        neighborhood: 'Jardim Alvorada',
        complement: null,
        reference: null,
        geoCoordinates: [-47.3952751159668, -20.56663703918457],
      },
    ],
    availableAddresses: [
      {
        addressType: null,
        receiverName: null,
        addressId: '93d75e8951bf4cb5af8add266541ab8e',
        isDisposable: true,
        postalCode: '14403132',
        city: 'Franca',
        state: 'SP',
        country: 'BRA',
        street: 'Rua José Fernando Peixe',
        number: null,
        neighborhood: 'Jardim Alvorada',
        complement: null,
        reference: null,
        geoCoordinates: [-47.3952751159668, -20.56663703918457],
      },
      {
        addressType: null,
        receiverName: null,
        addressId: '2cfdf73343ab4c6b855bf309fc816f8b',
        isDisposable: true,
        postalCode: '14403132',
        city: 'Franca',
        state: 'SP',
        country: 'BRA',
        street: 'Rua José Fernando Peixe',
        number: null,
        neighborhood: 'Jardim Alvorada',
        complement: null,
        reference: null,
        geoCoordinates: [-47.3952751159668, -20.56663703918457],
      },
      {
        addressType: null,
        receiverName: null,
        addressId: '42ec924f57434ef4ab12077fb0c6170c',
        isDisposable: true,
        postalCode: '14403132',
        city: 'Franca',
        state: 'SP',
        country: 'BRA',
        street: 'Rua José Fernando Peixe',
        number: null,
        neighborhood: 'Jardim Alvorada',
        complement: null,
        reference: null,
        geoCoordinates: [-47.3952751159668, -20.56663703918457],
      },
      {
        addressType: null,
        receiverName: null,
        addressId: '0de25c4057f2487c94f5b8bfe5213b40',
        isDisposable: true,
        postalCode: '14403132',
        city: 'Franca',
        state: 'SP',
        country: 'BRA',
        street: 'Rua José Fernando Peixe',
        number: null,
        neighborhood: 'Jardim Alvorada',
        complement: null,
        reference: null,
        geoCoordinates: [-47.3952751159668, -20.56663703918457],
      },
    ],
    pickupPoints: [],
  },
  clientProfileData: null,
  paymentData: {
    installmentOptions: [
      {
        paymentSystem: '1',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '2',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '3',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '6',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '7',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '8',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '9',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 14700,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 14700,
                total: 29400,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 9800,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 9800,
                total: 29400,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 7350,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 7350,
                total: 29400,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 5880,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 5880,
                total: 29400,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 4900,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 4900,
                total: 29400,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 4200,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 4200,
                total: 29400,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '16',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 29400,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 29400,
            total: 29400,
            sellerMerchantInstallments: [
              {
                id: 'BABADOTOP',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 29400,
                total: 29400,
              },
            ],
          },
        ],
      },
    ],
    paymentSystems: [
      {
        id: 6,
        name: 'Boleto Bancário',
        groupName: 'bankInvoicePaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '6',
        template: 'bankInvoicePaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 16,
        name: 'Vale',
        groupName: 'giftCardPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '16',
        template: 'giftCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 1,
        name: 'American Express',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^3[47][0-9]{13}$',
          mask: '9999 999999 99999',
          cardCodeRegex: '^[0-9]{4}$',
          cardCodeMask: '9999',
          weights: [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '1',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 9,
        name: 'Elo',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex:
            '^(50(67(0[78]|1[578]|2[012456789]|3[01234569]|4[0134567]|53|7[4-8])|9(0(0[0123478]|14|2[0-3]|3[0359]|4[012356789]|5[1-9]|6[0-9]|7[0134789]|8[04789]|9[123479])|1(0[3458]|4[6-9]|83)|2(20|5[7-9]|6[0-7])|4(0[7-9]|1[0-2]|31|57)|7(22|6[5-9])))|4(0117[89]|3(1274|8935)|5(1416|7(393|63[12])))|6(27780|36368|5(0(0(3[12356789]|4[0-7]|7[78])|4(0[6-9]|1[0-3]|2[4-8]|3[4-9]|8[5-9]|9[0-9])|5(0[012346789]|1[0-9]|2[0-9]|3[0178]|5[2-9]|6[0-4]|7[7-9]|8[0-9]|9[0-8])|72[0-7]|9(0[1-9]|1[0-9]|2[0128]|3[89]|4[6-9]|5[045]|6[25678]|71))|16(5[2-9]|6[0-9]|7[01456789])|50(0[0-9]|1[02345678]|36|5[1267])))\\d{0,13})$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '9',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 2,
        name: 'Visa',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^4[0-9]{15}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '2',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 3,
        name: 'Diners',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^3(0[0-5]|[68][0-9])[0-9]{11}$',
          mask: '9999 999999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '3',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 4,
        name: 'Mastercard',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex:
            '^((5(([1-2]|[4-5])[0-9]{8}|0((1|6)([0-9]{7}))|3(0(4((0|[2-9])[0-9]{5})|([0-3]|[5-9])[0-9]{6})|[1-9][0-9]{7})))|((508116)\\d{4,10})|((502121)\\d{4,10})|((589916)\\d{4,10})|(2[0-9]{15})|(67[0-9]{14})|(506387)\\d{4,10})',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '4',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 8,
        name: 'Hipercard',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^606282|^3841(?:[0|4|6]{1})0',
          mask: '9999999999999999999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '8',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
      {
        id: 7,
        name: 'Aura',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^50[0-9]{17}$',
          mask: '9999999999999999999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '7',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2020-10-26T14:00:36.0301249Z',
        availablePayments: null,
      },
    ],
    payments: [],
    giftCards: [],
    giftCardMessages: [],
    availableAccounts: [],
    availableTokens: [],
  },
  marketingData: null,
  sellers: [
    {
      id: '1',
      name: 'Babadotop',
      logo: '',
    },
  ],
  clientPreferencesData: {
    locale: 'pt-BR',
    optinNewsLetter: null,
  },
  commercialConditionData: null,
  storePreferencesData: {
    countryCode: 'BRA',
    saveUserData: true,
    timeZone: 'E. South America Standard Time',
    currencyCode: 'BRL',
    currencyLocale: 1046,
    currencySymbol: 'R$',
    currencyFormatInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: ',',
      currencyGroupSeparator: '.',
      currencyGroupSize: 3,
      startsWithCurrencySymbol: true,
    },
  },
  giftRegistryData: null,
  openTextField: null,
  invoiceData: null,
  customData: null,
  itemMetadata: {
    items: [
      {
        id: '287107498',
        seller: '1',
        name: 'Macacão estampado cinto all is love P',
        skuName: 'P',
        productId: '1902421',
        refId: '153869_898_0_P',
        ean: '0005110000000010P',
        imageUrl:
          'http://babadotop.vteximg.com.br/arquivos/ids/532702-548-806/000511principal--5-.jpg?v=637375143776730000',
        detailUrl: '/macacao-estampado-cinto-all-is-love-2021005001970/p',
        assemblyOptions: [],
      },
    ],
  },
  hooksData: null,
  ratesAndBenefitsData: {
    rateAndBenefitsIdentifiers: [
      {
        id: '189b7d15-fb58-4ebf-9f1f-d8371d133e89',
        name: 'PROMO | 25% | VER21 | ALL IS LOVE | 20.08 / 20.09',
        featured: false,
        description: 'Ago: All is Love l Set: All is Love',
        matchedParameters: {
          'Seller@CatalogSystem': '1|inclusive',
          'productCluster@CatalogSystem': '847,1060|inclusive',
        },
        additionalInfo: null,
      },
    ],
    teaser: [],
  },
  subscriptionData: null,
  itemsOrdination: null,
};
